### ISSUE TITLE
Not running on Windows 11

### ISSUE THREAD

**Issue by Darknessaep** [Colonial-Dev/satpaper#21]
I just downloaded the Windows Binary and opened as administrator but it is instantly closing again. 
Any clues would be greatly appreciated.

**Comment by Colonial-Dev** [comment]
Sounds like a panic. Could you run the binary from CMD or Powershell and see if you get an error message?

**Comment by Colonial-Dev** [comment]
Ah, wait, I wasn't thinking straight when I replied originally. Satpaper only works from the command line - it's closing immediately because you aren't providing the required arguments.

I don't use Windows often, but I think you can either create a shortcut to the binary that specifies the required arguments (see the `README` for those) or use a batch script. Not sure how to make it run in the background, but I'm fairly certain there's a way.

Let me know if that helps!

**Comment by Darknessaep** [comment]
Thank you for your time!
Everything works fine now, I will find out the rest.
Very nice Program!
